# -*- coding: utf-8 -*-
"""Exercise3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OuOp0xrxm1ydqlGA4kg3C9Bewek8aPqL
"""

def bfs(start_user):
    visited = [start_user]
    queue = [start_user]
    bfs_order = []

    while len(queue) > 0:
        current = queue.pop(0)
        bfs_order.append(current)

        for friend in current.friends:
            if friend not in visited:
                visited.append(friend)
                queue.append(friend)
    return bfs_order

def bfs_with_distances(start_user):
    distances = {start_user: 0}
    queue = [start_user]

    while len(queue) > 0:
        current = queue.pop(0)

        for friend in current.friends:
            if friend not in distances:
                distances[friend] = distances[current] + 1
                queue.append(friend)
    return distances

def shortest_path(start_user, target_user):
    parents = {start_user: None}
    queue = [start_user]

    while len(queue) > 0:
        current = queue.pop(0)
        if current == target_user:
            break

        for friend in current.friends:
            if friend not in parents:
                parents[friend] = current
                queue.append(friend)

    if target_user not in parents:
        return []

    path = []
    curr = target_user
    while curr is not None:
        path.insert(0, curr)
        curr = parents[curr]
    return path

def degrees_of_separation(start_user, target_user):
    distances = bfs_with_distances(start_user) # self. 삭제
    if target_user in distances:
        return distances[target_user]
    else:
        return -1

def friends_within_k_hops(start_user, k):
    distances = bfs_with_distances(start_user) # self. 삭제
    result = []
    for user in distances:
        if distances[user] <= k:
            result.append(user)
    return result

def compute_average_degrees_of_separation(all_users):
    total_distance = 0
    pairs_count = 0
    for start_user in all_users:
        distances = bfs_with_distances(start_user) # self. 삭제
        for target_user in distances:
            if start_user != target_user:
                total_distance += distances[target_user]
                pairs_count += 1
    if pairs_count == 0:
        return 0
    return total_distance / pairs_count

def get_distance_distribution(start_user):
    distances = bfs_with_distances(start_user) # self. 삭제
    distribution = {}
    for user in distances:
        d = distances[user]
        if d not in distribution:
            distribution[d] = 1
        else:
            distribution[d] += 1
    return distribution

def recommend_friends(start_user, max_recommendations=5):
    recs = {}
    my_friends = start_user.friends
    for friend in my_friends:
        for fof in friend.friends:
            if fof != start_user and fof not in my_friends:
                if fof not in recs:
                    recs[fof] = 1
                else:
                    recs[fof] += 1
    sorted_recs = sorted(recs.items(), key=lambda x: x[1], reverse=True)
    top_recs = [item[0] for item in sorted_recs[:max_recommendations]]
    return top_recs